// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceInfo() {
  return window['go']['main']['App']['GetDeviceInfo']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}
