// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetDeviceInfo():Promise<main.DeviceInfo>;

export function GetVersion():Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;
